var COMPONENTES = {};
COMPONENTES.USUARIO = 1;
COMPONENTES.CUPON = 2;
COMPONENTES.ESPECIALES = 3;
COMPONENTES.ASIGNACIONES = 4;
COMPONENTES.BLOQUEO = 5;
COMPONENTES.FERIADOSANIO = 6;
COMPONENTES.DIAPUENTE = 7;
COMPONENTES.ORGANIZACION = 8;
COMPONENTES.SUCURSAL = 9;

